### ISSUE TITLE
Is it possible in any way to have the soup commands run from a server?

### ISSUE THREAD

**Issue by Cotiiii** [Nettakrim/Souper-Secret-Settings#17]
Basically what I want is to make a mechanic that makes me put on a shader with the mod of souper secret settings, but I can't use mods on my server, just plugins, is there any way that the console recognizes commands from the souper secret settings to be able put a shader without the need for mod inside the server?

my server is in version paperspigot 1.21, I have seen that mods like Customizable Player Models which is a client mod has a plugin that allows the use of this same mod and without the need for the server to have a mod, basically the plugin makes the mod work, something like this can be done with this mod to make it compatible with servers that don't use mods server side?

**Comment by Nettakrim** [comment]
short answer yes, long answer not unless you know how to make plugins send packets

if the client also has another of my mods, [Client Execution](https://modrinth.com/mod/client-execution), then [when it receives a packet](https://github.com/Nettakrim/Client-Execution/blob/main/src/client/java/com/nettakrim/client_execution/ClientExecutionNetwork.java) with id `client_execution:execute_client` (and the packet data is just a single string), the client will try run it as a command, allowing any client-side only commands to be run

this would normally be easy to work with because client execution defines [the server-to-client payload](https://github.com/Nettakrim/Client-Execution/blob/main/src/main/java/com/nettakrim/client_execution/CommandPayload.java) and [a command to send it](https://github.com/Nettakrim/Client-Execution/blob/main/src/main/java/com/nettakrim/client_execution/ExecuteClientCommand.java), but to get it working from a paper/spigot server youd need a plugin to make the packet itself

**Comment by Cotiiii** [comment]
I'm so glad you're still active on this, they usually don't respond that fast!

What you mean is that you can make a plugin that runs the command?

In my case, I don't know anything about creating plugins :(

**Comment by Nettakrim** [comment]
yeah a plugin could add a command sends the same thing the mod does to clients

if i remeber i might try do so, but im decently busy right now and might forget by the time im more free lol

**Comment by Cotiiii** [comment]
seriously it would be incredible, this shader thing is something that excites me a lot and I would love to do mechanics with it, if possible whenever you want and can, do it in paperspigot 1.21 or other versions it would be incredible

**Comment by Nettakrim** [comment]
yeah it gets so over the top with /soup:stack, the 1.21.3 version will be even cooler as im rewriting everything to have even more customisation

**Comment by Cotiiii** [comment]
Hey, how are you doing? would you like to speak in md de discord? I want to ask you some things

my discord is: cotii_

**Comment by Nettakrim** [comment]
ive sent a friend request, i do also have a discord server for my mods https://discord.com/invite/XRAPg5AsBV
